### ISSUE TITLE
Compilation failures caused by xtensor-stack/xtensor#2923

### ISSUE THREAD

**Issue by krivenko** [xtensor-stack/xtensor-blas#258]
Recently I have been getting the following compilation errors when trying to use xtensor-blas in my project.

```
In file included from /home/runner/work/ezARPACK/ezARPACK/example/xtensor.example.cpp:22:
In file included from /home/runner/work/ezARPACK/ezARPACK/include/ezarpack/storages/xtensor.hpp:18:
In file included from /home/runner/xtensor.installed/include/xtensor-blas/xlinalg.hpp:28:
In file included from /home/runner/xtensor.installed/include/xtensor-blas/xblas.hpp:23:
/home/runner/xtensor.installed/include/xtensor-blas/xblas_utils.hpp:34:27: error: no template named 'has_data_interface'; did you mean 'has_simd_interface'?
   34 |     ) -> std::enable_if_t<has_data_interface<std::decay_t<T>>::value && std::decay_t<T>::static_layout == L, T&&>
      |                           ^~~~~~~~~~~~~~~~~~
      |                           has_simd_interface
/home/runner/xtensor.installed/include/xtensor/containers/../containers/../containers/../utils/xtensor_simd.hpp:268:12: note: 'has_simd_interface' declared here
  268 |     struct has_simd_interface : detail::has_simd_interface_impl<E, T>
      |            ^
In file included from /home/runner/work/ezARPACK/ezARPACK/example/xtensor.example.cpp:22:
In file included from /home/runner/work/ezARPACK/ezARPACK/include/ezarpack/storages/xtensor.hpp:18:
In file included from /home/runner/xtensor.installed/include/xtensor-blas/xlinalg.hpp:28:
In file included from /home/runner/xtensor.installed/include/xtensor-blas/xblas.hpp:23:
/home/runner/xtensor.installed/include/xtensor-blas/xblas_utils.hpp:41:11: error: no template named 'has_data_interface'; did you mean 'has_simd_interface'?
   41 |         (!has_data_interface<std::decay_t<T>>::value || I::static_layout != L)
      |           ^~~~~~~~~~~~~~~~~~
      |           has_simd_interface
/home/runner/xtensor.installed/include/xtensor/containers/../containers/../containers/../utils/xtensor_simd.hpp:268:12: note: 'has_simd_interface' declared here
  268 |     struct has_simd_interface : detail::has_simd_interface_impl<E, T>
      |            ^
In file included from /home/runner/work/ezARPACK/ezARPACK/example/xtensor.example.cpp:22:
In file included from /home/runner/work/ezARPACK/ezARPACK/include/ezarpack/storages/xtensor.hpp:18:
In file included from /home/runner/xtensor.installed/include/xtensor-blas/xlinalg.hpp:28:
In file included from /home/runner/xtensor.installed/include/xtensor-blas/xblas.hpp:23:
/home/runner/xtensor.installed/include/xtensor-blas/xblas_utils.hpp:50:11: error: no template named 'has_data_interface'; did you mean 'has_simd_interface'?
   50 |         (!has_data_interface<std::decay_t<T>>::value || I::static_layout != L)
      |           ^~~~~~~~~~~~~~~~~~
      |           has_simd_interface
/home/runner/xtensor.installed/include/xtensor/containers/../containers/../containers/../utils/xtensor_simd.hpp:268:12: note: 'has_simd_interface' declared here
  268 |     struct has_simd_interface : detail::has_simd_interface_impl<E, T>
      |            ^
```

The likely source of the problem is xtensor-stack/xtensor#2923.

**Comment by JohanMabille** [comment]
This change is not part of a release, so we haven't updated xtensor-blas yet. It should build with xtensor 0.27.1.

**Comment by krivenko** [comment]
@JohanMabille Thank you for the clarification, I have updated my workflows to install the latest tagged versions of xtensor components instead of using `master`.

**Comment by JohanMabille** [comment]
Closing it since it should be solved, do not hesitate to reopen it if you have any issue with latest xtensor tag.
